### ISSUE TITLE
Unable to create a post

### ISSUE THREAD

**Issue by FahadLive** [sapientabdullah/secret-journal#1]
I can't enter into the editor, the last thing I can do is shown in the given screenshot. If I press `Enter` it quits the program.
![image](https://github.com/user-attachments/assets/ed89c855-ac29-4e34-b043-d050f8f20b87)

I have aliased command `vim` to launch `nvim`. Is that the problem? If so, I think you should specify the requirement of `vim` in [Installation](https://github.com/sapientabdullah/secret-journal#installation)

**Comment by sapientabdullah** [comment]
Thank you for reporting this issue. I'll add support for Neovim and editor flexibility ASAP.

**Comment by sapientabdullah** [comment]
@Ranger-NF, please run `npm install -g secret-journal@latest` to get the fixed version. You can check out the [README](https://github.com/sapientabdullah/secret-journal#readme) for more information on the editor features. If you encounter any other issues, feel free to create a new one, and I'll take care of it immediately.

**Comment by FahadLive** [comment]
@sapientabdullah Awesome job! I just tested it out and it works. Will try using it daily. (Sorry to take so long to reply)

But I would like to know if it can be made compatible with something like [Daily You](https://github.com/Demizo/Daily_You). I know it would completely destroy the idea of encryption but I would use it more often if it was usable across different platforms (secret-journal for linux, daily you for android, etc.). Maybe, an option to turn off encryption?

NB: This is just a suggestion, feel free to take this project as you wish :)
